### ISSUE TITLE
Building iOS Framework Fails - functions and methods must return either zero or one values, and optionally an error

### ISSUE THREAD

**Issue by shallquist** [ProtonMail/gopenpgp#12]
Running gomobile bind -target ios generates following error:
```
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1231ee7]

goroutine 1 [running]:
golang.org/x/mobile/bind.(*funcSummary).asMethod(0x0, 0xc000b41f20, 0xd, 0xc002ccaed0)
	/Users/steighallquist/go/src/golang.org/x/mobile/bind/genobjc.go:558 +0x37
golang.org/x/mobile/bind.(*ObjcGen).genStructH(0xc000b41f20, 0xc0011c54f0, 0xc001cd6ea0)
	/Users/steighallquist/go/src/golang.org/x/mobile/bind/genobjc.go:1139 +0xdd3
golang.org/x/mobile/bind.(*ObjcGen).GenH(0xc000b41f20, 0x18, 0x13ab440)
	/Users/steighallquist/go/src/golang.org/x/mobile/bind/genobjc.go:187 +0x1736
main.genPkg(0x7ffeefbffa35, 0x4, 0xc0002ffbd0, 0xc0027a7780, 0xb, 0x10, 0xc0003c4090, 0x5, 0x5, 0x0, ...)
	/Users/steighallquist/go/src/golang.org/x/mobile/cmd/gobind/gen.go:144 +0x183a
main.run()
	/Users/steighallquist/go/src/golang.org/x/mobile/cmd/gobind/main.go:158 +0xa4a
main.main()
	/Users/steighallquist/go/src/golang.org/x/mobile/cmd/gobind/main.go:45 +0x78
```

**Comment by dsanghan** [comment]
@wussler Commit https://github.com/ProtonMail/gopenpgp/commit/e65ed17b416091e26cb61c2d2ae33ce6185e7737 seems to be causing this. Moving to commit before this one removes this particular error - maybe the change to `ReadClearSignedMessage` in `armor.go` that's returning 3 things is causing it?

**Comment by wussler** [comment]
The whole new structure was based on returning the detached verification status and the cleartext message split in different vars. See #17 .

**Comment by AMELkhdfjd** [comment]
hi [wussler](https://github.com/wussler)
I still have the error message when trying to bind to iOS, was the bug resolved ?

```
functions and methods must return either zero or one value, and optionally an error: Collector.ClearOfflineProxies
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1023df7c4]

goroutine 1 [running]:
golang.org/x/mobile/bind.(*funcSummary).asMethod(0x0, 0x14017d077d8)
        /Users/mel337zoti1820/go/pkg/mod/golang.org/x/mobile@v0.0.0-20240520174638-fa72addaaa1b/bind/genobjc.go:558 +0x24
golang.org/x/mobile/bind.(*ObjcGen).genStructH(0x14017d077d8, 0x14006cd0320, 0x14011d47e00)
        /Users/mel337zoti1820/go/pkg/mod/golang.org/x/mobile@v0.0.0-20240520174638-fa72addaaa1b/bind/genobjc.go:1141 +0xb0c
golang.org/x/mobile/bind.(*ObjcGen).GenH(0x14017d077d8)

```
